name: JacobPalm.dk
author: Jacob Palm
description: Homepage of Jacob Palm, Danish IT-professional, hobby coder and author of the Costa GUI.
keywords: costa, gui, jacob, palm, qbasic, vbdos, visual, basic, walrus, hvalrossen, vb, qb, quickbasic, dos, shell, pascal
lang: en
markdown: kramdown
baseURL: https://jacobpalm.dk

kramdown:
  syntax_highlighter: rouge

collections:
  projects:
    output: false
